USE gracaKids;

CREATE TABLE Endereco (
cod INTEGER NOT NULL UNIQUE,
rua VARCHAR (40) NOT NULL,
numero INTEGER,
bairro VARCHAR (30) NOT NULL,
cidade VARCHAR (30) NOT NULL,
uf CHAR (2) NOT NULL DEFAULT 'SC',
cep INTEGER NOT NULL,
obs VARCHAR (90),
PRIMARY KEY (cod));
