USE gracaKids;

CREATE TABLE Evento (
cod INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
nome VARCHAR (40) NOT NULL,
objetivo VARCHAR (50) NOT NULL,
tipoEvento VARCHAR (35) NOT NULL,
publicoAlvo VARCHAR (30) NOT NULL,
qtdPessoas INTEGER,
dataEvento DATE NOT NULL,
hora TIME NOT NULL,
duracao TIME NOT NULL,
cronograma VARCHAR (300) NOT NULL,
materiais VARCHAR (100),
qtdMateriais VARCHAR (150),
orcamento REAL NOT NULL,
fornecedores VARCHAR (100) NOT NULL,
equipe VARCHAR (200) NOT NULL,
escalaMinistros VARCHAR (100),
infInscricao VARCHAR (90) NOT NULL,
listaPresenca VARCHAR (350) NOT NULL,
fotoDivulgacao VARCHAR (60),
divulgacao VARCHAR (50) NOT NULL,
obs VARCHAR (100),
relatorio VARCHAR (150),
ministro INTEGER,
endereco INTEGER,
PRIMARY KEY (cod),
FOREIGN KEY (ministro) REFERENCES Ministro (cod),
FOREIGN KEY (endereco) REFERENCES Endereco (cod));
