USE gracaKids;

CREATE TABLE Aluno (
cod INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
nome VARCHAR (50) NOT NULL,
login VARCHAR (15) NOT NULL UNIQUE,
CHECK (CHAR_LENGTH(login) >= 5),
senha VARCHAR (10) NOT NULL,
CHECK (CHAR_LENGTH(senha) >= 5),
dataNasc DATE NOT NULL,
rg VARCHAR (14) NOT NULL UNIQUE,
cpf CHAR (14) NOT NULL UNIQUE,
fone INTEGER,
email VARCHAR (70) UNIQUE,
nEmergencial VARCHAR (50) NOT NULL,
nacionalidade VARCHAR (30),
linguaNativa VARCHAR (15),
linguaEstrangeira VARCHAR (30),
escolaAtual VARCHAR (50),
comorbidades VARCHAR (50),
aspectoPsi VARCHAR (50),
medicamentos VARCHAR (60),
alergias VARCHAR (50),
restricaoA VARCHAR (100),
projetoIgreja VARCHAR (60),
ministroAuxiliar BOOLEAN NOT NULL,
imagem VARCHAR (60) NOT NULL,
obs VARCHAR (100),
endereco INTEGER,
genero INTEGER,
tipoSanguineo INTEGER,
PRIMARY KEY (cod),
FOREIGN KEY (endereco) REFERENCES Endereco (cod),
FOREIGN KEY (genero) REFERENCES Genero (cod),
FOREIGN KEY (tipoSanguineo) REFERENCES TipoSanguineo (cod));
